name: basic-ds-env

channels:
  - conda-forge

dependencies:
  - python=3.8
  - jupyter
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib 
  - seaborn
  - networkx
  - Cython
# Modules for running in a Jupyter notebook
  - nb_conda_kernels
  - ipykernel
  - jupytext

