name: basic-ds-env

channels:
  - conda-forge

dependencies:
  - python=3.8
  - jupyter
  - nb_conda_kernels
  - ipykernel
  - jupytext
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn=0.24
  - matplotlib 

